[phases.setup]
nixPkgs = ['python39', 'gcc']

[phases.install]
cmds = ['python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json']

[start]
cmd = 'gunicorn web_app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120'
